spring:
  profiles:
    active: local # ????? ? ?????
    group:
      local_server: local_server, common, secret
      blue_server: blue_server, common, secret
      green_server: green_server, common, secret
# ??? ???? ???? (?? ?? ??? ?????)

---

spring:
  config:
    activate:
      on-profile: local_server
server:
  port: 8080
client:
  address: http://localhost:3000 # ?? ?? ? ??? ??
---

spring:
  config:
    activate:
      on-profile: blue_server
server:
  port: 8080
client:
  address: http://localhost:3000
---

spring:
  config:
    activate:
      on-profile: green_server
server:
  port: 9090
  
# ? ?? ???? ??? ??
---
spring:
  config:
    activate:
      on-profile: common
mybatis:
  mapper-locations:
    - mappers/*.xml